version: '2'
volumes:
  sv:
    driver: nfs
    driver_opts:
      share: "192.168.178.21/volume1/video"
services:
  mydb:
    image: mysql
    volumes:
      - ../mydata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
  pmcapp:
    build: 
      context: .
      dockerfile: my.Dockerfile
    environment:
      RAILS_ENV: development
    command: bundle exec rails s -p 2000 -b '0.0.0.0' -e development
    volumes:
      - .:/myapp
      - /media/osboxes/mediapart:/media
      - sv:/synivideo
    ports:
      - "2000:2000"
    depends_on:
      - mydb
  webserver2:
    build: 
      context: .
      dockerfile: mynginx.Dockerfile
    volumes:
      - /media/osboxes/mediapart:/usr/share/nginx/html
    ports:
      - "80:80"
